language: python
python:
  - "2.7"
  
#https://github.com/BenevolentCoders/rpi-python
#check out this to run a proper virtual environment maybe?
services:
  - docker

before_install:
  - curl -L https://github.com/BenevolentCoders/rpi-python
  - docker run -d --name python benevolentcoders/rpi-python python -c 'print u"Hello World"'

install:
  #normal libraries
  - pip install RPi.GPIO
  
# command to run tests
script: 
  #will fail cuz gpio only on raspi but whatever
  - python GooeyPi.py
